version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ShopApp
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./shopapp-backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      PORT: 8088
    depends_on:
      - db
    ports:
      - "8088:8088"

  frontend:
    build:
      context: ./shopapp-frontend
      dockerfile: Dockerfile
    environment:
      API_URL: http://backend:8088/api/v1
    depends_on:
      - backend
    ports:
      - "80:80"
